### ISSUE TITLE
Build the Apk 

### ISSUE THREAD

**Issue by ByteJoseph** [croodles/Schoolbook#1]
Build the APK output of this project and share it here. Please help

```bash
cordova platform add android
```

```bash
cordova build android
```

**Comment by bajrangCoder** [comment]
go ahead and check out release section of this repo

**Comment by ByteJoseph** [comment]
> go ahead and check out release section of this repo

Thanks a million.

**Comment by ByteJoseph** [comment]
Thank you. Can you share your ```cordova requirements```
My ```cordova build``` not working.

**Comment by bajrangCoder** [comment]
I had also faced. But with right gradle and java version it works.

`cordova requirements`
- Java JDK: 17.0.12
- latest gradle(installed from arch repository): 8.10-1

**Comment by ByteJoseph** [comment]
> I had also faced. But with right gradle and java version it works.
> 
> `cordova requirements`
> 
> * Java JDK: 17.0.12
> * latest gradle(installed from arch repository): 8.10-1

This is my first time trying Cordova.Thank you very much for spending your valuable time.

**Comment by bajrangCoder** [comment]
> > I had also faced. But with right gradle and java version it works.
> > `cordova requirements`
> > 
> > * Java JDK: 17.0.12
> > * latest gradle(installed from arch repository): 8.10-1
> 
> This is my first time trying Cordova.Thank you very much for spending your valuable time.

I will suggest use another framework, as Cordova is deprecated and you will miss features.
If you want something similar like Cordova then check capacitor or use other like React native, tauri, etc..
